# Fix: Final YAML, combining the working JAR download (5.6.4) to enable gradlew, 
# and then forcing gradlew to update to the desired 9.1.0 version (which uses the reliable ZIP distribution).
workflows:
  android-build:
    name: Android Build and Release
    environment:
      vars:
        CM_JAVA_VERSION: 17
        CM_ANDROID_SDK_BUILD_TOOLS: 34.0.0
        CM_ANDROID_SDK_PLATFORM_TOOLS: 34.0.0
        CM_ANDROID_SDK_PLATFORM: 34
        GRADLE_USER_HOME: $CM_BUILD_DIR/.gradle 
      
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: master
          include: true
        - pattern: develop
          include: true
        - pattern: feature/.*
          include: true
    
    scripts:
      # 1: إعداد SDK - تم تصحيح مشكلة المسار
      - name: Set up Android SDK
        script: |
          SDK_MANAGER="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager"
          echo "Setting up Android SDK Build Tools $CM_ANDROID_SDK_BUILD_TOOLS, Platform Tools $CM_ANDROID_SDK_PLATFORM_TOOLS, Platform $CM_ANDROID_SDK_PLATFORM"
          
          yes | $SDK_MANAGER "build-tools;$CM_ANDROID_SDK_BUILD_TOOLS" "platform-tools" "platforms;android-$CM_ANDROID_SDK_PLATFORM"
          yes | $SDK_MANAGER --licenses
      
      # 2: إنشاء المجلد
      - name: Create Gradle Wrapper directory
        script: |
          mkdir -p gradle/wrapper
          
      # 3: الإصلاح: تنزيل JAR قديم ومستقر (5.6.4) لتمكين gradlew. (الأمر الذي فشل سابقًا سيعمل الآن لأن الـ JAR متاح)
      - name: Download Stable Gradle Wrapper JAR (5.6.4)
        script: |
          # نستخدم رابط 5.6.4 لأنه موثوق به لتنزيل الـ JAR الصغير
          curl -f -L -o gradle/wrapper/gradle-wrapper.jar https://services.gradle.org/distributions/gradle-5.6.4-wrapper.jar
      
      # 4: منح الأذونات
      - name: Grant gradlew permission
        script: |
          chmod +x gradlew
      
      # 5: تحديث الـ Wrapper إلى 9.1.0 (سيقوم الـ JAR الذي تم تنزيله بتنزيل ZIP 9.1.0-bin.zip الجديد)
      - name: Update Gradle Distribution to 9.1.0 (Using Wrapper)
        script: |
          # هذا هو الأمر الذي يستخدم الـ JAR الذي تم تنزيله لتنزيل ملف ZIP الكامل 9.1.0
          ./gradlew wrapper --gradle-version 9.1.0
          
      - name: Run Android Lint and Build Android Release Bundle (Final Build Step)
        script: |
          ./gradlew lintRelease
          ./gradlew bundleRelease
          ./gradlew assembleRelease
          
      - name: List build outputs
        script: |
          ls -R app/build/outputs
          
    artifacts:
      - build/app/outputs/**/*.aab
      - build/app/outputs/**/*.apk
      - build/reports/**/*.html
      
    publishing:
      email:
        recipients:
          - your_email@example.com
        notify:
          success: true
          failure: false