workflows:
  android-build:
    name: Android Build and Release
    environment:
      vars:
        CM_JAVA_VERSION: 17
        CM_ANDROID_SDK_BUILD_TOOLS: 34.0.0
        CM_ANDROID_SDK_PLATFORM_TOOLS: 34.0.0
        CM_ANDROID_SDK_PLATFORM: 34
        # تحديد المسار الصحيح لمخبأ Gradle Cache
        GRADLE_USER_HOME: $CM_BUILD_DIR/.gradle 
      
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: master
          include: true
        - pattern: develop
          include: true
        - pattern: feature/.*
          include: true
    
    scripts:
      - name: Set up Android SDK
        script: |
          SDK_MANAGER="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager"
          echo "Setting up Android SDK Build Tools $CM_ANDROID_SDK_BUILD_TOOLS, Platform Tools $CM_ANDROID_SDK_PLATFORM_TOOLS, Platform $CM_ANDROID_SDK_PLATFORM"
          
          yes | $SDK_MANAGER "build-tools;$CM_ANDROID_SDK_BUILD_TOOLS" "platform-tools" "platforms;android-$CM_ANDROID_SDK_PLATFORM"
          yes | $SDK_MANAGER --licenses
      
      - name: Grant gradlew permission
        script: |
          # هذه الخطوة ستنجح الآن لأنك قمت بإضافة الملف gradle-wrapper.jar
          chmod +x gradlew
          
      - name: Download and Set up Gradle Distribution
        script: |
          # هذا الأمر سيقوم بتشغيل الـ Wrapper، الذي سيقوم بتنزيل ملف ZIP الكامل (9.1.0) تلقائياً، وتثبيته، والبدء في بناء التبعيات.
          ./gradlew dependencies --no-daemon
          
      - name: Run Android Lint and Build Android Release Bundle (Final Build Step)
        script: |
          ./gradlew lintRelease
          ./gradlew bundleRelease
          ./gradlew assembleRelease
          
      - name: List build outputs
        script: |
          ls -R app/build/outputs
          
    artifacts:
      - build/app/outputs/**/*.aab
      - build/app/outputs/**/*.apk
      - build/reports/**/*.html
      
    publishing:
      email:
        recipients:
          - your_email@example.com
        notify:
          success: true
          failure: false