# Fix: Final YAML - Removing all failed JAR downloads. Directly downloading and extracting the full Gradle 9.1.0-bin.zip.
workflows:
  android-build:
    name: Android Build and Release
    environment:
      vars:
        CM_JAVA_VERSION: 17
        CM_ANDROID_SDK_BUILD_TOOLS: 34.0.0
        CM_ANDROID_SDK_PLATFORM_TOOLS: 34.0.0
        CM_ANDROID_SDK_PLATFORM: 34
        GRADLE_USER_HOME: $CM_BUILD_DIR/.gradle 
      
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: master
          include: true
        - pattern: develop
          include: true
        - pattern: feature/.*
          include: true
    
    scripts:
      # 1: إعداد SDK - تم تصحيح مشكلة المسار
      - name: Set up Android SDK
        script: |
          SDK_MANAGER="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager"
          echo "Setting up Android SDK Build Tools $CM_ANDROID_SDK_BUILD_TOOLS, Platform Tools $CM_ANDROID_SDK_PLATFORM_TOOLS, Platform $CM_ANDROID_SDK_PLATFORM"
          
          yes | $SDK_MANAGER "build-tools;$CM_ANDROID_SDK_BUILD_TOOLS" "platform-tools" "platforms;android-$CM_ANDROID_SDK_PLATFORM"
          yes | $SDK_MANAGER --licenses
      
      # 2: إنشاء المجلد
      - name: Create Gradle Wrapper directory
        script: |
          mkdir -p gradle/wrapper
          
      # 3: الإصلاح الجذري: تنزيل ZIP الثنائي لـ Gradle 9.1.0
      - name: Download and Extract Gradle 9.1.0 Distribution ZIP
        script: |
          # تنزيل ملف الـ ZIP الثنائي الكامل مباشرة
          curl -f -L -o gradle.zip https://services.gradle.org/distributions/gradle-9.1.0-bin.zip
          
          # فك ضغط الملف داخل مجلد gradle/wrapper
          unzip gradle.zip -d gradle/wrapper
          
          # نقل محتويات مجلد gradle-9.1.0 إلى gradle/wrapper
          mv gradle/wrapper/gradle-9.1.0/lib/gradle-wrapper.jar gradle/wrapper/gradle-wrapper.jar
          
      # 4: منح الأذونات
      - name: Grant gradlew permission
        script: |
          chmod +x gradlew
          
      # 5: تشغيل البناء (لن تحتاج هذه الخطوة إلى التنزيل مرة أخرى)
      - name: Run Android Lint and Build Android Release Bundle (Final Build Step)
        script: |
          ./gradlew lintRelease
          ./gradlew bundleRelease
          ./gradlew assembleRelease
          
      - name: List build outputs
        script: |
          ls -R app/build/outputs
          
    artifacts:
      - build/app/outputs/**/*.aab
      - build/app/outputs/**/*.apk
      - build/reports/**/*.html
      
    publishing:
      email:
        recipients:
          - your_email@example.com
        notify:
          success: true
          failure: false