workflows:
  android-build:
    name: Android Build
    instance_type: mac_mini_m1 # Recommended for Android builds on Codemagic
    max_build_duration: 60 # Set a maximum build duration in minutes

    trigger:
      branch: main # Build on pushes to the 'main' branch

    environment:
      android_sdk: latest # Use the latest Android SDK available on Codemagic
      java: openjdk17 # Use OpenJDK 17 for modern Android development

    scripts:
      - name: Create tessdata directory
        run: |
          mkdir -p app/src/main/assets/tessdata

      - name: Download Tesseract Arabic traineddata
        run: |
          curl -L -o app/src/main/assets/tessdata/ara.traineddata https://github.com/tesseract-ocr/tessdata_fast/raw/main/ara.traineddata

      - name: Run Android Lint
        run: |
          ./gradlew lintRelease

      - name: Build Android Release APK
        run: |
          ./gradlew assembleRelease

      - name: Build Android Release AAB
        run: |
          ./gradlew bundleRelease

    artifacts:
      - app/build/outputs/apk/**/*.apk
      - app/build/outputs/bundle/**/*.aab
      - app/build/reports/**/*.xml # Include lint and test reports

    publishing:
      email:
        recipients:
          - your.email@example.com # Replace with your email address
        success:
          enabled: true
        failure:
          enabled: true