# Fix: Final YAML, removing the manual JAR download and relying on the existing gradlew script
# to fetch the full Gradle distribution ZIP (7.2), which is more stable.
workflows:
  android-build:
    name: Android Build and Release
    environment:
      vars:
        CM_JAVA_VERSION: 17
        CM_ANDROID_SDK_BUILD_TOOLS: 34.0.0
        CM_ANDROID_SDK_PLATFORM_TOOLS: 34.0.0
        CM_ANDROID_SDK_PLATFORM: 34
        GRADLE_USER_HOME: $CM_BUILD_DIR/.gradle 
      
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: master
          include: true
        - pattern: develop
          include: true
        - pattern: feature/.*
          include: true
    
    scripts:
      # 1: إعداد SDK - تم تصحيح مشكلة المسار
      - name: Set up Android SDK
        script: |
          SDK_MANAGER="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager"
          echo "Setting up Android SDK Build Tools $CM_ANDROID_SDK_BUILD_TOOLS, Platform Tools $CM_ANDROID_SDK_PLATFORM_TOOLS, Platform $CM_ANDROID_SDK_PLATFORM"
          
          yes | $SDK_MANAGER "build-tools;$CM_ANDROID_SDK_BUILD_TOOLS" "platform-tools" "platforms;android-$CM_ANDROID_SDK_PLATFORM"
          yes | $SDK_MANAGER --licenses
      
      # 2: إنشاء المجلد
      - name: Create Gradle Wrapper directory
        script: |
          mkdir -p gradle/wrapper
          
      # 3: منح الأذونات فقط. (تم حذف خطوة التنزيل اليدوية الفاشلة)
      - name: Grant gradlew permission (Ensure gradlew is executable)
        script: |
          chmod +x gradlew
      
      # 4: إعادة تشغيل الـ Wrapper لتنزيل ZIP الخاص بـ Gradle (هذا يحل مشكلة ClassNotFound)
      - name: Download Gradle Distribution (Using Wrapper)
        script: |
          # هذه الخطوة تجعل gradlew ينزل ملف gradle-7.2-bin.zip (أو ما تم تحديده في gradle-wrapper.properties)
          # هذا هو الإصلاح لـ "ClassNotFoundException"
          ./gradlew wrapper --gradle-version 7.2
          
      - name: Run Android Lint and Build Android Release Bundle (Final Build Step)
        script: |
          ./gradlew lintRelease
          ./gradlew bundleRelease
          ./gradlew assembleRelease
          
      - name: List build outputs
        script: |
          ls -R app/build/outputs
          
    artifacts:
      - build/app/outputs/**/*.aab
      - build/app/outputs/**/*.apk
      - build/reports/**/*.html
      
    publishing:
      email:
        recipients:
          - your_email@example.com
        notify:
          success: true
          failure: false