workflows:
  android-build:
    name: Android Build
    instance_type: mac_mini_m1
    max_build_duration: 60

    environment:
      java: 11

    # Corrected: Set the working directory to the subdirectory where gradlew is located.
    # This typically resolves "gradlew: No such file or directory" when the Android project
    # is not in the repository root, but in a subfolder like 'android'.
    working_directory: android 

    scripts:
      - name: Download missing Gradle Wrapper JAR
        script: |
          curl -L -o gradle/wrapper/gradle-wrapper.jar https://services.gradle.org/distributions/gradle-8.8-wrapper.jar

      - name: Grant execute permissions to gradlew
        script: |
          find . -name gradlew -exec chmod +x {} \;

      - name: Create tessdata directory
        script: |
          mkdir -p app/src/main/assets/tessdata

      - name: Download Tesseract Arabic traineddata
        script: |
          curl -L -o app/src/main/assets/tessdata/ara.traineddata https://github.com/tesseract-ocr/tessdata_fast/raw/main/ara.traineddata

      - name: Run Android Lint
        script: |
          ./gradlew lintRelease

      - name: Build Android Release APK
        script: |
          ./gradlew assembleRelease

      - name: Build Android Release AAB
        script: |
          ./gradlew bundleRelease

    artifacts:
      - app/build/outputs/apk/**/*.apk
      - app/build/outputs/bundle/**/*.aab
      - app/build/reports/**/*.xml

    publishing:
      email:
        recipients:
          - your.email@example.com