workflows:
  android-build:
    name: Android Build
    instance_type: mac_mini_m1
    max_build_duration: 60

    environment:
      java: 11

    scripts:
      - name: Grant execute permissions to gradlew
        script: |
          chmod +x gradlew

      - name: Create tessdata directory
        script: |
          mkdir -p app/src/main/assets/tessdata

      - name: Download Tesseract Arabic traineddata
        script: |
          curl -L -o app/src/main/assets/tessdata/ara.traineddata https://github.com/tesseract-ocr/tessdata_fast/raw/main/ara.traineddata

      - name: Run Android Lint
        script: |
          ./gradlew lintRelease

      - name: Build Android Release APK
        script: |
          ./gradlew assembleRelease

      - name: Build Android Release AAB
        script: |
          ./gradlew bundleRelease

    artifacts:
      - app/build/outputs/apk/**/*.apk
      - app/build/outputs/bundle/**/*.aab
      - app/build/reports/**/*.xml

    publishing:
      email:
        recipients:
          - your.email@example.com