# Fix: Final script-based fix. Downloads the reliable Wrapper JAR from Maven Central and renames it to the required name.
workflows:
  android-build:
    name: Android Build and Release
    environment:
      vars:
        CM_JAVA_VERSION: 17
        CM_ANDROID_SDK_BUILD_TOOLS: 34.0.0
        CM_ANDROID_SDK_PLATFORM_TOOLS: 34.0.0
        CM_ANDROID_SDK_PLATFORM: 34
        GRADLE_USER_HOME: $CM_BUILD_DIR/.gradle 
      
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: master
          include: true
        - pattern: develop
          include: true
        - pattern: feature/.*
          include: true
    
    scripts:
      # 1: إعداد SDK
      - name: Set up Android SDK
        script: |
          SDK_MANAGER="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager"
          echo "Setting up Android SDK Build Tools $CM_ANDROID_SDK_BUILD_TOOLS, Platform Tools $CM_ANDROID_SDK_PLATFORM_TOOLS, Platform $CM_ANDROID_SDK_PLATFORM"
          
          yes | $SDK_MANAGER "build-tools;$CM_ANDROID_SDK_BUILD_TOOLS" "platform-tools" "platforms;android-$CM_ANDROID_SDK_PLATFORM"
          yes | $SDK_MANAGER --licenses
      
      # 2: الإصلاح الجذري: تنزيل ملف JAR الصحيح من Maven Central وتغيير اسمه
      - name: Download and Rename Correct Gradle Wrapper JAR (from Maven Central)
        script: |
          mkdir -p gradle/wrapper
          # هذا الرابط يحتوي على الكلاس المفقود وهو مستقر جداً. ننزله ونسميه gradle-wrapper.jar
          curl -f -L -o gradle/wrapper/gradle-wrapper.jar https://repo1.maven.org/maven2/org/gradle/gradle-wrapper/6.7.1/gradle-wrapper-6.7.1.jar
      
      # 3: منح الأذونات
      - name: Grant gradlew permission
        script: |
          chmod +x gradlew
          
      # 4: تنزيل وتجهيز توزيع Gradle
      - name: Download and Set up Gradle Distribution (Triggered by Wrapper)
        script: |
          # سيعمل هذا الأمر الآن. سيجد الـ JAR التمهيدي (6.7.1) ويقوم بتنزيل الـ ZIP (9.1.0) كما هو محدد في gradle-wrapper.properties
          ./gradlew dependencies --no-daemon
          
      - name: Run Android Lint and Build Android Release Bundle (Final Build Step)
        script: |
          ./gradlew lintRelease
          ./gradlew bundleRelease
          ./gradlew assembleRelease
          
      - name: List build outputs
        script: |
          ls -R app/build/outputs
          
    artifacts:
      - build/app/outputs/**/*.aab
      - build/app/outputs/**/*.apk
      - build/reports/**/*.html
      
    publishing:
      email:
        recipients:
          - your_email@example.com
        notify:
          success: true
          failure: false