workflows:
  android-build:
    name: Android Build and Release
    environment:
      vars:
        CM_JAVA_VERSION: 17
        CM_ANDROID_SDK_BUILD_TOOLS: 34.0.0
        CM_ANDROID_SDK_PLATFORM_TOOLS: 34.0.0
        CM_ANDROID_SDK_PLATFORM: 34
        # تحديد المسار الصحيح لمخزن Gradle Cache
        GRADLE_USER_HOME: $CM_BUILD_DIR/.gradle 
      
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: master
          include: true
        - pattern: develop
          include: true
        - pattern: feature/.*
          include: true
    
    scripts:
      # 1: إعداد SDK
      - name: Set up Android SDK
        script: |
          SDK_MANAGER="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager"
          echo "Setting up Android SDK Build Tools $CM_ANDROID_SDK_BUILD_TOOLS, Platform Tools $CM_ANDROID_SDK_PLATFORM_TOOLS, Platform $CM_ANDROID_SDK_PLATFORM"
          
          yes | $SDK_MANAGER "build-tools;$CM_ANDROID_SDK_BUILD_TOOLS" "platform-tools" "platforms;android-$CM_ANDROID_SDK_PLATFORM"
          yes | $SDK_MANAGER --licenses
      
      # 2: منح الأذونات (ضروري دائمًا)
      - name: Grant gradlew permission (MANDATORY)
        script: |
          chmod +x gradlew
          
      # 3: تشغيل أول أمر Gradle (سيقوم هذا الأمر الآن بتنزيل ملف ZIP الكامل 9.1.0 تلقائياً)
      # إذا كان ملف gradlew نفسه مفقودًا، يجب على المستخدم التأكد من وجوده في المشروع.
      - name: Download and Set up Gradle Distribution (Triggered by Wrapper)
        script: |
          # نستخدم أمر بسيط لـ Gradle. إذا كان ملف gradle-wrapper.properties مُعدًا لاستخدام 9.1.0، فسيتم تنزيله هنا.
          # هذا هو المكان الذي سيتم فيه تنزيل ملف ZIP (gradle-9.1.0-bin.zip)
          ./gradlew dependencies --no-daemon
          
      - name: Run Android Lint and Build Android Release Bundle (Final Build Step)
        script: |
          ./gradlew lintRelease
          ./gradlew bundleRelease
          ./gradlew assembleRelease
          
      - name: List build outputs
        script: |
          ls -R app/build/outputs
          
    artifacts:
      - build/app/outputs/**/*.aab
      - build/app/outputs/**/*.apk
      - build/reports/**/*.html
      
    publishing:
      email:
        recipients:
          - your_email@example.com
        notify:
          success: true
          failure: false
