workflows:
  android-build:
    name: Android Build and Release

    environment:
      vars:
        CM_JAVA_VERSION: 17
        CM_ANDROID_SDK_BUILD_TOOLS: 34.0.0
        CM_ANDROID_SDK_PLATFORM_TOOLS: 34.0.0
        CM_ANDROID_SDK_PLATFORM: 34
        GRADLE_USER_HOME: $CM_BUILD_DIR/.gradle

    cache:
      paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
        - $CM_BUILD_DIR/.android/build-cache

    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: master
          include: true
        - pattern: develop
          include: true
        - pattern: feature/.*
          include: true

    scripts:
      - name: Set up Java
        script: |
          echo "Using Java version $CM_JAVA_VERSION"

      - name: Build Android APK
        script: |
          ./gradlew assembleRelease

      - name: List build outputs
        script: |
          ls -R app/build/outputs

    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
